version: '3'

services:
  server:
    image: 'golang:latest'
    volumes:
      - ".:/home"
    working_dir: "/home"
    command: ["go", "run", "main.go"]
    ports:
      - 50051:50051
    depends_on:
      - db

  grpcui:
    image: 'wongnai/grpcui:latest'
    environment:
      - GRPCUI_SERVER=server:50051
      - GRPCUI_PORT=8080
    ports:
      - 8080:8080
    volumes:
      - ./grpcui:/home
    command: ["sh", "-c", "/home/wait-for-it.sh server:50051 -- /usr/local/scripts/start.sh"]
    depends_on:
      - server
      - db
      - grafana

  db:
    image: 'postgres:latest'
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=p@ssw0rd
    ports:
      - 5432:5432

  grafana:
    image: 'grafana/grafana:latest'
    volumes:
      - "./grafana:/var/lib/grafana"
    depends_on:
      - db
    ports:
      - 3000:3000
